services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./mongo_main_data:/data/db
  
  backend:
    build: 
      context: ./backend
      target: production
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "0.0.0.0:3000:3000"
    env_file: ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:5173:5173"