services:
  mongodb:
    volumes: !override
      - mongo_data:/finance_dashboard/staging/data/db
  
  backend:
    ports: !override
      - "3001:3000"

  frontend:
    ports: !override
      - "5174:5173"